import '../models/user.dart';
import '../models/need.dart';
import '../models/donation.dart';
import '../models/match.dart';

class SampleDataService {
  static List<NGO> getSampleNGOs() {
    return [
      NGO(
        id: 'ngo_1',
        name: 'Akshaya Patra Foundation',
        email: 'contact@akshayapatra.org',
        phone: '+91-80-30143400',
        city: 'Mumbai',
        registrationNumber: 'NGO-123456',
        missionStatement: 'To eliminate classroom hunger by implementing the Mid-Day Meal Programme',
        focusAreas: ['Education', 'Child Nutrition', 'Food Security'],
        createdAt: DateTime.now().subtract(const Duration(days: 365)),
        isVerified: true,
      ),
      NGO(
        id: 'ngo_2',
        name: 'Smile Foundation',
        email: 'info@smilefoundation.org',
        phone: '+91-11-43123700',
        city: 'Delhi',
        registrationNumber: 'NGO-789012',
        missionStatement: 'To empower underprivileged children, youth and women through relevant education, innovative healthcare and market-focused livelihood programmes',
        focusAreas: ['Education', 'Healthcare', 'Women Empowerment'],
        createdAt: DateTime.now().subtract(const Duration(days: 200)),
        isVerified: true,
      ),
      NGO(
        id: 'ngo_3',
        name: 'Goonj NGO',
        email: 'mail@goonj.org',
        phone: '+91-11-26972351',
        city: 'Chennai',
        registrationNumber: 'NGO-345678',
        missionStatement: 'To bridge the gap between the cities and villages by channelizing material and intellectual resources',
        focusAreas: ['Rural Development', 'Material Donations', 'Community Development'],
        createdAt: DateTime.now().subtract(const Duration(days: 150)),
        isVerified: true,
      ),
    ];
  }

  static List<Individual> getSampleIndividuals() {
    return [
      Individual(
        id: 'ind_1',
        name: 'Priya Sharma',
        email: 'priya.sharma@email.com',
        phone: '+91-9876543210',
        city: 'Mumbai',
        needExplanation: 'Single mother of two children, working as a daily wage laborer',
        urgentNeeds: ['Winter clothing', 'School supplies', 'Food items'],
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
        isVerified: true,
      ),
      Individual(
        id: 'ind_2',
        name: 'Rajesh Kumar',
        email: 'rajesh.kumar@email.com',
        phone: '+91-9876543211',
        city: 'Delhi',
        needExplanation: 'Elderly person living alone, limited mobility',
        urgentNeeds: ['Medicines', 'Food supplies', 'Warm blankets'],
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
        isVerified: true,
      ),
      Individual(
        id: 'ind_3',
        name: 'Sunita Devi',
        email: 'sunita.devi@email.com',
        phone: '+91-9876543212',
        city: 'Chennai',
        needExplanation: 'Widow with three children, works as a domestic helper',
        urgentNeeds: ['Children\'s clothing', 'Educational materials', 'Kitchen utensils'],
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        isVerified: true,
      ),
    ];
  }

  static List<Need> getSampleNeeds() {
    return [
      Need(
        id: 'need_1',
        recipientId: 'ngo_1',
        recipientName: 'Akshaya Patra Foundation',
        recipientType: 'ngo',
        title: 'Urgent: Winter Blankets for Children',
        description: 'We urgently need 100 warm blankets for children in our Mumbai center before winter sets in. Our children are from extremely poor families and don\'t have adequate protection from cold.',
        requiredTags: ['blankets', 'winter', 'children', 'warm'],
        city: 'Mumbai',
        urgency: UrgencyLevel.urgent,
        status: NeedStatus.unmet,
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        quantity: 100,
      ),
      Need(
        id: 'need_2',
        recipientId: 'ngo_2',
        recipientName: 'Smile Foundation',
        recipientType: 'ngo',
        title: 'Educational Toys and Learning Materials',
        description: 'Seeking educational toys, puzzles, building blocks, and interactive learning materials for children aged 3-8 in our Delhi learning center. These help with cognitive development.',
        requiredTags: ['educational', 'toys', 'learning', 'children', 'development'],
        city: 'Delhi',
        urgency: UrgencyLevel.medium,
        status: NeedStatus.unmet,
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
        quantity: 50,
      ),
      Need(
        id: 'need_3',
        recipientId: 'ind_1',
        recipientName: 'Priya Sharma',
        recipientType: 'individual',
        title: 'Winter Coats for Two Children',
        description: 'I am a single mother working as a domestic helper. Need warm winter coats for my children (ages 5 and 8, boy and girl). Any gently used coats would be greatly appreciated.',
        requiredTags: ['winter', 'coats', 'children', 'clothing', 'warm'],
        city: 'Mumbai',
        urgency: UrgencyLevel.high,
        status: NeedStatus.unmet,
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        quantity: 2,
      ),
      Need(
        id: 'need_4',
        recipientId: 'ind_2',
        recipientName: 'Rajesh Kumar',
        recipientType: 'individual',
        title: 'Canned Food and Essential Medicines',
        description: 'I am an elderly person living alone with diabetes and high blood pressure. Need non-perishable food items and financial help for medicines. Limited mobility makes shopping difficult.',
        requiredTags: ['food', 'canned', 'medicines', 'diabetes', 'elderly'],
        city: 'Delhi',
        urgency: UrgencyLevel.urgent,
        status: NeedStatus.unmet,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        quantity: 1,
      ),
      Need(
        id: 'need_5',
        recipientId: 'ngo_3',
        recipientName: 'Goonj NGO',
        recipientType: 'ngo',
        title: 'School Supplies for Rural Children',
        description: 'Collecting notebooks, pens, pencils, erasers, rulers, and drawing materials for 200 children in rural Tamil Nadu villages. These children walk 5+ km to school daily.',
        requiredTags: ['school', 'supplies', 'notebooks', 'stationery', 'educational', 'rural'],
        city: 'Chennai',
        urgency: UrgencyLevel.medium,
        status: NeedStatus.unmet,
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        quantity: 200,
      ),
      Need(
        id: 'need_6',
        recipientId: 'ngo_1',
        recipientName: 'Akshaya Patra Foundation',
        recipientType: 'ngo',
        title: 'Rice and Pulses for Mid-Day Meals',
        description: 'We serve 5000+ children daily in Mumbai. Need bulk quantity of rice (1000kg) and mixed pulses (500kg) for our mid-day meal program. Help us fight classroom hunger.',
        requiredTags: ['rice', 'pulses', 'food', 'bulk', 'grains', 'nutrition'],
        city: 'Mumbai',
        urgency: UrgencyLevel.high,
        status: NeedStatus.unmet,
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        quantity: 1500,
      ),
      Need(
        id: 'need_7',
        recipientId: 'ind_3',
        recipientName: 'Sunita Devi',
        recipientType: 'individual',
        title: 'Women\'s Work Clothes and Kitchen Items',
        description: 'I am a widow supporting three children through domestic work. Need practical work clothes (sarees/salwar suits) and basic kitchen utensils like plates, cups, cooking pots.',
        requiredTags: ['clothing', 'women', 'kitchen', 'utensils', 'work', 'practical'],
        city: 'Chennai',
        urgency: UrgencyLevel.medium,
        status: NeedStatus.unmet,
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        quantity: 5,
      ),
      Need(
        id: 'need_8',
        recipientId: 'ngo_2',
        recipientName: 'Smile Foundation',
        recipientType: 'ngo',
        title: 'Computers and Electronics for Skill Training',
        description: 'Setting up a computer training center for underprivileged youth in Delhi. Need 10 working computers/laptops, keyboards, mouse, and basic electronics for skill development.',
        requiredTags: ['computers', 'laptops', 'electronics', 'training', 'skill', 'youth', 'technology'],
        city: 'Delhi',
        urgency: UrgencyLevel.medium,
        status: NeedStatus.unmet,
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
        quantity: 15,
      ),
      Need(
        id: 'need_9',
        recipientId: 'ngo_3',
        recipientName: 'Goonj NGO',
        recipientType: 'ngo',
        title: 'Footwear for Village Children',
        description: 'Many children in remote villages walk barefoot to school. We need shoes, sandals, and slippers in various sizes (age 5-15) to protect their feet from rough terrain.',
        requiredTags: ['footwear', 'shoes', 'sandals', 'children', 'village', 'school', 'protection'],
        city: 'Chennai',
        urgency: UrgencyLevel.high,
        status: NeedStatus.unmet,
        createdAt: DateTime.now().subtract(const Duration(days: 6)),
        quantity: 150,
      ),
      Need(
        id: 'need_10',
        recipientId: 'ind_1',
        recipientName: 'Priya Sharma',
        recipientType: 'individual',
        title: 'School Bag and Study Materials',
        description: 'My children need new school bags as theirs are torn. Also need basic study materials like compass box, colors, drawing books for the new academic session.',
        requiredTags: ['school', 'bags', 'study', 'materials', 'children', 'educational', 'academic'],
        city: 'Mumbai',
        urgency: UrgencyLevel.medium,
        status: NeedStatus.unmet,
        createdAt: DateTime.now().subtract(const Duration(hours: 18)),
        quantity: 3,
      ),
    ];
  }

  static List<Donation> getSampleDonations() {
    return [
      Donation(
        id: 'donation_1',
        donorId: 'donor_1',
        itemName: 'Premium Winter Blankets - Pack of 5',
        description: 'Brand new thermal blankets, extra warm and soft. Perfect for children and adults. Machine washable, hypoallergenic material.',
        contextDescription: 'Bought in bulk but only used 2 out of 7. Remaining 5 are unopened and brand new. Ideal for winter protection.',
        tags: ['blankets', 'winter', 'thermal', 'warm', 'children', 'new'],
        imageUrl: 'assets/images/winter_blankets.jpeg',
        city: 'Mumbai',
        status: DonationStatus.available,
        createdAt: DateTime.now().subtract(const Duration(hours: 3)),
      ),
      Donation(
        id: 'donation_2',
        donorId: 'donor_2',
        itemName: 'Rice Bags - 25kg Premium Basmati',
        description: 'High quality basmati rice, 5 bags of 5kg each. Fresh stock, perfect for cooking meals for large groups.',
        contextDescription: 'Bought for a function that got cancelled. All bags are sealed and have 2 years expiry date.',
        tags: ['rice', 'food', 'grains', 'bulk', 'nutrition', 'basmati'],
        imageUrl: 'assets/images/rice_bags.jpeg',
        city: 'Mumbai',
        status: DonationStatus.available,
        createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      ),
      Donation(
        id: 'donation_3',
        donorId: 'donor_3',
        itemName: 'Educational Toys and Games Set',
        description: 'Collection of 15 educational toys including puzzles, building blocks, alphabet games, and math toys for kids aged 3-8.',
        contextDescription: 'My children outgrew these toys. All pieces are complete and toys are sanitized. Great for learning and development.',
        tags: ['educational', 'toys', 'learning', 'children', 'puzzles', 'blocks', 'games'],
        imageUrl: 'assets/images/educational_toys.webp',
        city: 'Delhi',
        status: DonationStatus.available,
        createdAt: DateTime.now().subtract(const Duration(hours: 12)),
      ),
      Donation(
        id: 'donation_4',
        donorId: 'donor_4',
        itemName: 'Working Laptop - Dell Inspiron',
        description: 'Dell Inspiron laptop in good working condition. 8GB RAM, 500GB storage. Ideal for students or basic computer training.',
        contextDescription: 'Upgraded to new laptop. This one works perfectly, battery lasts 3-4 hours. Includes charger.',
        tags: ['laptop', 'computer', 'electronics', 'training', 'technology', 'dell', 'working'],
        imageUrl: 'assets/images/laptop_dell.jpg',
        city: 'Delhi',
        status: DonationStatus.available,
        createdAt: DateTime.now().subtract(const Duration(hours: 8)),
      ),
      Donation(
        id: 'donation_5',
        donorId: 'donor_5',
        itemName: 'School Supplies Bundle',
        description: 'Complete school supplies kit: 50 notebooks, 100 pens, pencils, erasers, rulers, compass sets, and art materials.',
        contextDescription: 'Bought wholesale for my stationery shop but have excess stock. All items are brand new and good quality.',
        tags: ['school', 'supplies', 'notebooks', 'stationery', 'educational', 'pens', 'pencils'],
        imageUrl: 'assets/images/school_supplies.jpeg',
        city: 'Chennai',
        status: DonationStatus.available,
        createdAt: DateTime.now().subtract(const Duration(hours: 4)),
      ),
      Donation(
        id: 'donation_6',
        donorId: 'donor_6',
        itemName: 'Children\'s Footwear Collection',
        description: 'Assorted children\'s shoes and sandals in various sizes (age 5-12). Mix of sports shoes, school shoes, and casual sandals.',
        contextDescription: 'Collected from family and friends whose children outgrew them. All are clean and in good condition.',
        tags: ['footwear', 'shoes', 'sandals', 'children', 'school', 'sports', 'various'],
        imageUrl: 'assets/images/children_shoes.jpeg',
        city: 'Chennai',
        status: DonationStatus.available,
        createdAt: DateTime.now().subtract(const Duration(hours: 18)),
      ),
      Donation(
        id: 'donation_7',
        donorId: 'donor_7',
        itemName: 'Canned Food & Nutrition Pack',
        description: 'Variety pack of 20 canned foods: vegetables, pulses, soups, and fruits. All with long expiry dates.',
        contextDescription: 'Stocked up during lockdown but have excess. All cans are unopened and have 1-2 years validity.',
        tags: ['canned', 'food', 'nutrition', 'vegetables', 'pulses', 'non-perishable', 'variety'],
        imageUrl: 'assets/images/canned_food_variety.jpeg',
        city: 'Delhi',
        status: DonationStatus.available,
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      Donation(
        id: 'donation_8',
        donorId: 'donor_8',
        itemName: 'Women\'s Practical Clothing',
        description: 'Collection of 8 cotton sarees and 5 salwar suits in good condition. Practical colors suitable for daily work.',
        contextDescription: 'Clearing my wardrobe. These are gently used but well-maintained clothes in practical designs.',
        tags: ['clothing', 'women', 'sarees', 'salwar', 'cotton', 'practical', 'work'],
        imageUrl: 'assets/images/women_clothing.jpeg',
        city: 'Chennai',
        status: DonationStatus.available,
        createdAt: DateTime.now().subtract(const Duration(hours: 14)),
      ),
      Donation(
        id: 'donation_9',
        donorId: 'donor_9',
        itemName: 'Kitchen Utensils & Cookware Set',
        description: 'Complete kitchen set: 5 steel plates, 8 cups, 3 cooking pots, serving spoons, and basic utensils.',
        contextDescription: 'Downsizing home and have duplicate kitchen items. All are stainless steel and in excellent condition.',
        tags: ['kitchen', 'utensils', 'cookware', 'plates', 'cups', 'pots', 'steel', 'practical'],
        imageUrl: 'assets/images/kitchen_utensils.jpeg',
        city: 'Chennai',
        status: DonationStatus.available,
        createdAt: DateTime.now().subtract(const Duration(hours: 9)),
      ),
      Donation(
        id: 'donation_10',
        donorId: 'donor_10',
        itemName: 'School Bags & Study Materials',
        description: '6 sturdy school bags with multiple compartments, plus geometry sets, color boxes, and drawing books.',
        contextDescription: 'My children\'s friends outgrew these. Bags have wheels and are very durable. Study materials are barely used.',
        tags: ['school', 'bags', 'study', 'materials', 'geometry', 'colors', 'drawing', 'durable'],
        imageUrl: 'assets/images/school_bags.jpeg',
        city: 'Mumbai',
        status: DonationStatus.available,
        createdAt: DateTime.now().subtract(const Duration(hours: 7)),
      ),
      Donation(
        id: 'donation_11',
        donorId: 'donor_11',
        itemName: 'Winter Coats for Kids',
        description: 'Three warm winter coats for children - sizes small, medium, and large. Excellent protection from cold weather.',
        contextDescription: 'My children outgrew these but they\'re still in great condition. Zippers work perfectly, very warm lining.',
        tags: ['winter', 'coats', 'children', 'clothing', 'warm', 'protection', 'jackets'],
        imageUrl: 'assets/images/kids_winter_coats.jpeg',
        city: 'Mumbai',
        status: DonationStatus.available,
        createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      ),
      Donation(
        id: 'donation_12',
        donorId: 'donor_12',
        itemName: 'Computers & Accessories',
        description: '2 desktop computers with monitors, keyboards, mouse. Basic specs but perfect for learning and training.',
        contextDescription: 'Office upgrade left us with working computers. All components tested and functional. Great for computer training.',
        tags: ['computers', 'desktop', 'monitors', 'keyboard', 'mouse', 'training', 'technology', 'learning'],
        imageUrl: 'assets/images/desktop_computers.jpg',
        city: 'Delhi',
        status: DonationStatus.available,
        createdAt: DateTime.now().subtract(const Duration(hours: 11)),
      ),
    ];
  }

  static List<Match> getSampleMatches() {
    return [
      Match(
        id: 'match_1',
        donationId: 'donation_1',
        needId: 'need_1',
        donorId: 'donor_1',
        recipientId: 'ind_1', // Changed from 'recipient_1' to 'ind_1'
        matchScore: 0.95,
        status: MatchStatus.pending,
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      Match(
        id: 'match_2',
        donationId: 'donation_2',
        needId: 'need_2',
        donorId: 'donor_2',
        recipientId: 'ngo_1',
        matchScore: 0.87,
        status: MatchStatus.accepted,
        createdAt: DateTime.now().subtract(const Duration(hours: 4)),
        acceptedAt: DateTime.now().subtract(const Duration(hours: 3)),
      ),
      Match(
        id: 'match_3',
        donationId: 'donation_1',
        needId: 'need_3',
        donorId: 'donor_1',
        recipientId: 'ngo_2',
        matchScore: 0.76,
        status: MatchStatus.pending,
        createdAt: DateTime.now().subtract(const Duration(hours: 1)),
      ),
      Match(
        id: 'match_4',
        donationId: 'donation_3',
        needId: 'need_1',
        donorId: 'donor_3',
        recipientId: 'ind_2', // Added another match for ind_2
        matchScore: 0.82,
        status: MatchStatus.pending,
        createdAt: DateTime.now().subtract(const Duration(minutes: 30)),
      ),
    ];
  }
}
